spring:
  datasource:
    url: jdbc:h2:file:${user.home}/.h2/transferdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: transfer
    password: transfer
  h2:
    console:
      enabled: true
      path: /h2-console
